
version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PW:-postgres}
      POSTGRES_DB: ${PG_DB:-mydb}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  back:
    build: ./back
    environment:
      DATABASE_URL: postgres://${PG_USER:-postgres}:${PG_PW:-postgres}@db:5432/${PG_DB:-mydb}
    depends_on:
      db:
        condition: service_healthy

  front:
    build: ./front
    ports:
      - "3000:80"
    depends_on:
      - back

volumes:
  pgdata:
